#!/usr/bin/env python3
"""HOTSPOT「多欄下拉」批次 —— 單選子集（12 題）。

這批的原始題型是下拉選單 HOTSPOT，但每題只有一個空格、單一正解，
本質就是單選題，直接組成跟 az900_manual.CHOICE 一樣的形狀。

3 題來源官方答案段（sections[4]）本身就是壞的（跟自己的選項分析矛盾、
或是把候選項目原文整段複製當成答案），改採來源自己選項分析裡的判定
（id 168/199/276）。id 328 是另一種矛盾：來源標記的選項本身跟它自己
嵌入的官方參考文件衝突，兩者選了參考文件（並附上 Microsoft Learn 連結）；
id 215/399 的候選選項來源沒有給全，用 render_az900.py 截圖核對過。
"""

DROPDOWN_SINGLE = {
    126: {
        'stem_zh': '你需要估算將地端 Microsoft SQL 伺服器遷移到 Azure 後，因減少用電量而節省的成本。你應該使用哪一項工具？',
        'stem_en': 'You need to estimate the cost savings due to reduced electricity consumption as a result of migrating on-premises Microsoft SQL servers to Azure. Which tool should you use?',
        'options': {
            'A': ('The Azure Migrate: Server Assessment tool', 'Azure Migrate：伺服器評估工具'),
            'B': ('The Azure Total Cost of Ownership (TCO) calculator', 'Azure 整體擁有成本計算機 (TCO Calculator)'),
            'C': ('The Database Migration Assistant', '資料庫遷移小幫手 (Database Migration Assistant)'),
            'D': ('The pricing calculator in Azure', 'Azure 定價計算機'),
        },
        'answer': ['B'],
        'explanations': {
            'A': 'Server Assessment 工具用於評估地端伺服器是否適合遷移、建議合適的 Azure VM 規格與遷移可行性，並不會計算用電量減少所帶來的成本節約。',
            'B': 'TCO 計算機正是設計來比較地端資料中心與 Azure 之間的整體成本，其中一項比較項目就是電力等機房營運成本；把地端 SQL 伺服器的用電量等資訊輸入後，就能估算搬上 Azure 可以省下多少用電成本。',
            'C': 'Database Migration Assistant 用於評估資料庫相容性與遷移前的準備工作，聚焦在資料庫層面，不會計算用電成本節約。',
            'D': 'Azure 定價計算機用來估算在 Azure 上執行資源預估要花多少錢，並不會拿地端用電成本來做比較分析。',
        },
    },
    289: {
        'stem_zh': '下列關於 Azure 中國的敘述，何者正確？',
        'stem_en': 'Which of the following statements about Azure China is correct?',
        'options': {
            'A': ('Azure China is operated by Microsoft.', 'Azure 中國是由 Microsoft 營運的。'),
            'B': ('Azure China has feature parity with Azure global.', 'Azure 中國與全球版 Azure 的功能完全相同。'),
            'C': ('Azure China services can be accessed from China only.', 'Azure 中國的服務只能從中國境內存取。'),
            'D': ('Azure China is a distinct separate instance of Microsoft Azure.', 'Azure 中國是 Microsoft Azure 的一個獨立、分開的執行個體。'),
        },
        'answer': ['D'],
        'explanations': {
            'A': 'Azure 中國實際上是由世紀互聯 (21Vianet) 負責營運，並非由 Microsoft 直接營運，這是 Azure 中國跟其他區域 Azure 最大的差異之一。',
            'B': 'Azure 中國雖然與全球版 Azure 有許多相同的服務與功能，但受限於當地法規與獨立運作模式，兩者的服務項目與更新時程並不完全一致，並非功能完全對等。',
            'C': 'Azure 中國提供的服務，全球各地的使用者都可以存取（例如用來服務在中國有業務的跨國企業），並非僅限中國境內才能存取。',
            'D': 'Azure 中國是與全球版 Azure 完全分開、獨立運作的一個執行個體，由世紀互聯依中國法規獨立營運與維護，資料也儲存在中國境內的資料中心，這正是它與全球 Azure 之間關係的正確描述。',
        },
    },
    97: {
        'stem_zh': '你打算將公司的網路延伸到 Azure。該網路包含一台 IP 位址為 131.107.200.1 的 VPN 設備。你需要在 Azure 中建立一個定義該 VPN 設備的 Azure 資源。你應該建立哪一種 Azure 資源？',
        'stem_en': "You plan to extend your company's network to Azure. The network contains a VPN appliance that uses an IP address of 131.107.200.1. You need to create an Azure resource that defines the VPN appliance in Azure. Which Azure resource should you create?",
        'options': {
            'A': ('NAT gateways', 'NAT 閘道'),
            'B': ('Application gateways', '應用程式閘道 (Application Gateway)'),
            'C': ('Local network gateways', '本機網路閘道 (Local Network Gateway)'),
            'D': ('Virtual network gateways', '虛擬網路閘道 (Virtual Network Gateway)'),
            'E': ('On-premises Data Gateways', '內部部署資料閘道 (On-premises Data Gateway)'),
            'F': ('Azure Data Box Gateway', 'Azure Data Box Gateway'),
            'G': ('Azure Stack Edge / Data Box Gateway', 'Azure Stack Edge / Data Box Gateway'),
            'H': ('Web Application Firewall policies', 'Web 應用程式防火牆原則 (WAF policies)'),
        },
        'answer': ['C'],
        'explanations': {
            'A': 'NAT 閘道用於管理輸出流量的網路位址轉譯，與定義內部部署 VPN 設備無關。',
            'B': '應用程式閘道是七層（應用層）負載平衡與 Web 應用程式防火牆服務，不用於描述 VPN 設備。',
            'C': '本機網路閘道 (Local Network Gateway) 是 Azure 中用來代表內部部署 VPN 設備的資源物件，會記錄該設備的公用 IP 位址與位址空間，因此符合題目需求。',
            'D': '虛擬網路閘道用於在 Azure 端建立 VPN/ExpressRoute 連線，但它代表的是 Azure 這一端，而不是內部部署的 VPN 設備。',
            'E': '內部部署資料閘道用於連接內部資料來源與 Power BI 等雲端服務，與 VPN 設備的定義無關。',
            'F': 'Azure Data Box Gateway 是用於大量資料搬遷至 Azure 的實體/虛擬裝置，與 VPN 設備無關。',
            'G': 'Azure Stack Edge 是邊緣運算與資料傳輸裝置，與定義 VPN 設備無關。',
            'H': 'WAF 原則是用來保護 Web 應用程式免受攻擊，與 VPN 設備的定義無關。',
        },
    },
    109: {
        'stem_zh': '你打算建立一部 Azure 虛擬機器。你需要確定必須使用哪一種儲存體服務來儲存虛擬機器的非受控 (unmanaged) 資料磁碟。你應該選擇哪一項服務？',
        'stem_en': 'You plan to create an Azure virtual machine. You need to identify which storage service must be used to store the unmanaged data disks of the virtual machine. What should you identify?',
        'options': {
            'A': ('Containers', '容器 (Blob 容器)'),
            'B': ('File shares', '檔案共用 (File shares)'),
            'C': ('Tables', '資料表 (Tables)'),
            'D': ('Queues', '佇列 (Queues)'),
        },
        'answer': ['A'],
        'explanations': {
            'A': '非受控磁碟是以分頁 Blob 的形式，儲存在儲存體帳戶的 Blob 容器中，因此建立虛擬機器的非受控資料磁碟時需要使用容器。',
            'B': '檔案共用是透過 SMB 通訊協定提供的共用檔案儲存服務，並非用來存放虛擬機器的非受控磁碟。',
            'C': '資料表儲存體用於存放結構化的 NoSQL 資料，與虛擬機器磁碟儲存無關。',
            'D': '佇列儲存體用於應用程式之間的訊息傳遞，與虛擬機器磁碟儲存無關。',
        },
    },
    112: {
        'stem_zh': '你打算實作一套 Azure 資料庫解決方案。你需要實作一個符合下列需求的資料庫解決方案：\n‧ 可以同時從多個地區新增資料\n‧ 可以儲存 JSON 文件\n你應該部署哪一種資料庫服務？',
        'stem_en': 'You plan to implement an Azure database solution. You need to implement a database solution that meets the following requirements: can add data concurrently from multiple regions; can store JSON documents. Which database service should you deploy?',
        'options': {
            'A': ('Azure Cosmos DB', 'Azure Cosmos DB'),
            'B': ('Azure Database for MySQL servers', 'Azure Database for MySQL 伺服器'),
            'C': ('Azure Database for MariaDB servers', 'Azure Database for MariaDB 伺服器'),
            'D': ('SQL Data warehouses', 'SQL 資料倉儲 (SQL Data Warehouse / Azure Synapse Analytics)'),
            'E': ('Azure Cache for Redis', 'Azure Cache for Redis'),
        },
        'answer': ['A'],
        'explanations': {
            'A': 'Azure Cosmos DB 是全球分散式、多模型資料庫服務，原生支援多個地區同時寫入，也能以文件模型儲存 JSON 資料，完全符合兩項需求。',
            'B': 'MySQL 是關聯式資料庫，資料需依結構描述儲存，並不原生支援多地區同時寫入，也不是為 JSON 文件儲存設計的服務。',
            'C': 'MariaDB 與 MySQL 同屬關聯式資料庫，同樣不支援多地區同時寫入與原生 JSON 文件儲存。',
            'D': 'SQL 資料倉儲（現為 Azure Synapse Analytics）主要用於巨量結構化資料的分析查詢，並非設計來支援多地區並行寫入或 JSON 文件儲存。',
            'E': 'Azure Cache for Redis 是記憶體內快取服務，用來加速資料存取，並非持久性的 JSON 文件資料庫，也不支援多地區寫入。',
        },
    },
    141: {
        'stem_zh': '你打算將虛擬機器移動到新的訂用帳戶。下列哪一項陳述正確描述了虛擬機器在訂用帳戶之間的移轉規則？',
        'stem_en': 'You plan to move virtual machines to a new subscription. Which statement correctly describes the rules for migrating virtual machines between subscriptions?',
        'options': {
            'A': ('The virtual machines cannot be moved to the new subscription.', '這些虛擬機器無法移動到新的訂用帳戶。'),
            'B': ('The virtual machines can be moved to the new subscription.', '這些虛擬機器可以移動到新的訂用帳戶。'),
            'C': ('The virtual machines can be moved to the new subscription only if they are all in the same resource group.', '只有當這些虛擬機器全部位於同一個資源群組時，才能移動到新的訂用帳戶。'),
            'D': ('The virtual machines can be moved to the new subscription only if they run Windows Server 2019.', '只有當這些虛擬機器執行 Windows Server 2019 時，才能移動到新的訂用帳戶。'),
        },
        'answer': ['B'],
        'explanations': {
            'A': 'Azure 允許將資源（包括虛擬機器）在訂用帳戶之間移動，只要來源與目的訂用帳戶符合移轉條件（例如同屬一個 Azure AD 租用戶且該資源類型支援跨訂用帳戶移動），因此「無法移動」的說法並不正確。',
            'B': 'Azure Resource Manager 支援將虛擬機器等資源從一個訂用帳戶移動到另一個訂用帳戶，只要目標訂用帳戶在同一個 Azure AD 租用戶下且資源類型支援移動即可，這是資源移轉功能的正確描述。',
            'C': '資源群組本身也可以被移動或重組，虛擬機器移轉並不要求所有虛擬機器都位於同一個資源群組中，因此此描述並不正確。',
            'D': '虛擬機器能否移動到新訂用帳戶與其作業系統版本（例如是否為 Windows Server 2019）無關，各種作業系統的虛擬機器都可以進行訂用帳戶移轉。',
        },
    },
    161: {
        'stem_zh': '你的 Azure 環境中包含 10 個 Web 應用程式。你應該連線到哪一個 URL 來管理所有的 Azure 資源？',
        'stem_en': 'You have an Azure environment that contains 10 web apps. To which URL should you connect to manage all the Azure resources?',
        'options': {
            'A': ('admin.azure.com', 'admin.azure.com'),
            'B': ('portal.azurewebsites.com', 'portal.azurewebsites.com'),
            'C': ('www.microsoft.com', 'www.microsoft.com'),
            'D': ('portal.azure.com', 'portal.azure.com'),
        },
        'answer': ['D'],
        'explanations': {
            'A': 'admin.azure.com 並不是 Azure 資源管理入口網站的網址，無法用來統一管理 Azure 資源。',
            'B': 'azurewebsites.net/com 是 Azure App Service（Web Apps）預設的應用程式網域，用於存取已部署的 Web 應用程式，而不是管理入口網站。',
            'C': 'www.microsoft.com 是微軟的官方網站，並非 Azure 資源的管理介面。',
            'D': 'portal.azure.com 是 Azure 入口網站（Azure portal）的正式網址，可在同一個介面統一檢視與管理所有 Azure 資源，包括 Web 應用程式、資料庫、虛擬機器、虛擬網路與儲存體等。',
        },
    },
    168: {
        'stem_zh': '你需要檢視可能影響 Azure 訂用帳戶可用性的計畫性維護事件清單。你應該從 Azure 入口網站使用哪一個 blade？',
        'stem_en': 'You need to view a list of planned maintenance events that can affect the availability of an Azure subscription. Which blade should you use from the Azure portal?',
        'options': {
            'A': ('Dashboard', '儀表板 (Dashboard)'),
            'B': ('Service Health', '服務健康情況 (Service Health)'),
            'C': ('Resource Groups', '資源群組 (Resource Groups)'),
            'D': ('Monitor', '監視 (Monitor)'),
        },
        'answer': ['B'],
        'explanations': {
            'A': '儀表板是使用者可自訂的檢視畫面，用來快速存取常用資源與資訊，並非專門用來查看計畫性維護事件的位置。',
            'B': '服務健康情況是 Azure 入口網站中專門用來檢視服務問題、計畫性維護事件與健康狀態通知的功能，正是查看可能影響訂用帳戶可用性之維護事件的正確位置。',
            'C': '資源群組用於組織與管理 Azure 資源，與檢視計畫性維護事件無關。',
            'D': '監視用於檢視資源的效能指標與診斷紀錄，並非設計用來檢視計畫性維護事件的功能。',
        },
    },
    199: {
        'stem_zh': '在 Azure 入口網站中，你應該使用哪一個節點，將 Reader 角色指派給某個資源群組的使用者？',
        'stem_en': 'Which node in the Azure portal should you use to assign a user the Reader role for a resource group?',
        'options': {
            'A': ('Overview', '概觀 (Overview)'),
            'B': ('Activity log', '活動記錄 (Activity log)'),
            'C': ('Access control (IAM)', '存取控制 (IAM) (Access control (IAM))'),
            'D': ('Tags', '標籤 (Tags)'),
            'E': ('Resource visualizer', '資源視覺化工具 (Resource visualizer)'),
            'F': ('Events', '事件 (Events)'),
            'G': ('Resource costs', '資源成本 (Resource costs)'),
            'H': ('Deployments', '部署 (Deployments)'),
            'I': ('Security', '安全性 (Security)'),
            'J': ('Policies', '原則 (Policies)'),
            'K': ('Properties', '屬性 (Properties)'),
        },
        'answer': ['C'],
        'explanations': {
            'A': '概觀節點顯示資源群組的名稱、位置、訂用帳戶等基本資訊，並沒有指派角色的功能。',
            'B': '活動記錄節點用於檢視資源群組的操作歷史紀錄，無法在此指派角色。',
            'C': '存取控制 (IAM) 節點是 Azure 入口網站中用來管理角色型存取控制 (RBAC) 的主要位置，可在此將 Reader 等角色指派給使用者、群組或服務主體，因此是正確答案。',
            'D': '標籤節點用於為資源加上鍵值標籤以利分類與計費管理，與角色指派無關。',
            'E': '資源視覺化工具用於以圖形方式呈現資源群組內資源之間的關聯，與角色指派無關。',
            'F': '事件節點用於檢視與資源相關的服務事件記錄，與角色指派無關。',
            'G': '資源成本節點用於檢視資源群組的成本與花費分析，與角色指派無關。',
            'H': '部署節點用於檢視與管理資源群組的部署歷程記錄，與角色指派無關。',
            'I': '安全性節點用於檢視資源群組的安全性建議與狀態（如 Defender for Cloud 的評分），與角色指派無關。',
            'J': '原則節點用於檢視與管理套用在資源群組上的 Azure Policy 合規性狀態，與角色指派無關。',
            'K': '屬性節點用於檢視資源群組的識別碼等屬性資訊，與角色指派無關。',
        },
    },
    215: {
        'stem_zh': '你需要透過 Azure Cloud Shell 管理 Azure。你應該在 Azure 入口網站的工具列中選擇哪一個圖示？',
        'stem_en': 'You need to manage Azure by using Azure Cloud Shell. Which Azure portal toolbar icon should you select?',
        'options': {
            'A': ('Cloud Shell (">_")', 'Cloud Shell（">_" 圖示）'),
            'B': ('Notifications (bell icon)', '通知（鈴鐺圖示）'),
            'C': ('Settings (gear icon)', '設定（齒輪圖示）'),
            'D': ('Feedback (smiley icon)', '意見反應（笑臉圖示）'),
        },
        'answer': ['A'],
        'explanations': {
            'A': '">_" 圖示就是 Azure Cloud Shell 的啟動按鈕，點擊後會在入口網站下方開啟內建的命令列視窗，可以選擇 Bash 或 PowerShell 環境，不需要在本機安裝任何工具。',
            'B': '鈴鐺圖示是通知中心，顯示部署狀態或服務健康等系統通知，跟開啟 Cloud Shell 無關。',
            'C': '齒輪圖示是入口網站的顯示設定，用來調整佈景主題、語言、時區等入口網站行為，不會開啟 Cloud Shell。',
            'D': '笑臉圖示是用來對 Azure 入口網站提供意見反應，跟管理 Azure 資源或開啟 Cloud Shell 無關。',
        },
    },
    276: {
        'stem_zh': '你在 Azure Resource Manager 中建立了一個名為 RG1 的資源群組。你需要防止 RG1 中的資源遭到意外刪除。你應該使用哪一種設定？',
        'stem_en': 'You create a resource group named RG1 in Azure Resource Manager. You need to prevent the accidental deletion of the resources in RG1. Which setting should you use?',
        'options': {
            'A': ('Quickstart', '快速入門 (Quickstart)'),
            'B': ('Resource costs', '資源成本 (Resource costs)'),
            'C': ('Deployments', '部署 (Deployments)'),
            'D': ('Policies', '原則 (Policies)'),
            'E': ('Properties', '屬性 (Properties)'),
            'F': ('Locks', '鎖定 (Locks)'),
            'G': ('Export template', '匯出範本 (Export template)'),
        },
        'answer': ['F'],
        'explanations': {
            'A': '快速入門是用來引導使用者了解如何開始使用 Azure 資源的教學功能，與防止資源被刪除無關。',
            'B': '資源成本用於檢視資源群組的花費與成本分析，無法防止資源被意外刪除。',
            'C': '部署用於檢視與管理資源群組的部署歷程記錄，無法防止資源被刪除。',
            'D': '原則可用來稽核與強制資源的合規性設定，但無法直接阻擋使用者刪除資源。',
            'E': '屬性用於顯示資源群組的識別碼等基本屬性，無法防止資源被刪除。',
            'F': '鎖定 (Locks) 可以在訂用帳戶、資源群組或資源層級套用 CanNotDelete（刪除鎖定）或 ReadOnly（唯讀鎖定），防止使用者意外刪除或修改重要資源，是正確答案。',
            'G': '匯出範本用於將資源群組的設定匯出成 ARM 範本，與防止資源被刪除無關。',
        },
    },
    328: {
        'stem_zh': '你需要向 Microsoft 申請提高公司訂用帳戶的配額限制。你應該使用 Azure 入口網站中的哪一個 blade？',
        'stem_en': 'You need to request that Microsoft increase a subscription quota limit for your company. Which blade should you use from the Azure portal?',
        'options': {
            'A': ('Create a resource', '建立資源 (Create a resource)'),
            'B': ('All services', '所有服務 (All services)'),
            'C': ('Dashboard', '儀表板 (Dashboard)'),
            'D': ('All resources', '所有資源 (All resources)'),
            'E': ('Resource groups', '資源群組 (Resource groups)'),
            'F': ('App Services', 'App Services'),
            'G': ('Function Apps', 'Function Apps'),
            'H': ('SQL databases', 'SQL 資料庫 (SQL databases)'),
            'I': ('Azure Cosmos DB', 'Azure Cosmos DB'),
            'J': ('Virtual machines', '虛擬機器 (Virtual machines)'),
            'K': ('Load balancers', '負載平衡器 (Load balancers)'),
            'L': ('Help + support', '說明及支援 (Help + support)'),
        },
        'answer': ['L'],
        'explanations': {
            'A': '建立資源用於在 Azure 入口網站中佈建全新的資源（例如虛擬機器、儲存體帳戶等），並不是提出配額調整申請的入口。',
            'B': '所有服務只是用來瀏覽 Azure 提供的所有服務類別清單，無法用來提交配額增加的支援要求。',
            'C': '儀表板是使用者自訂的資源檢視畫面，無法用來提交配額增加要求。',
            'D': '所有資源會列出訂用帳戶中目前擁有的所有資源，並非用來申請配額調整的位置。',
            'E': '資源群組用於管理資源的分組結構，與申請配額增加無關。',
            'F': 'App Services 是用來管理 Web 應用程式的服務，與申請配額增加無關。',
            'G': 'Function Apps 是用來管理無伺服器函式的服務，與申請配額增加無關。',
            'H': 'SQL 資料庫是用來管理 Azure SQL 資料庫的服務，與申請配額增加無關。',
            'I': 'Azure Cosmos DB 是用來管理分散式資料庫的服務，與申請配額增加無關。',
            'J': '虛擬機器是用來管理 VM 執行個體的服務，本身雖然會受配額限制，但並不是提出配額增加申請的入口。',
            'K': '負載平衡器是用來管理負載平衡資源的服務，與申請配額增加無關。',
            'L': '【答案校正】來源自己標記的正確選項是「Create a resource」，但這與其嵌入的官方參考文件矛盾——文件明確指出配額增加要透過「說明及支援 (Help + support)」提出標準配額增加要求（Microsoft Learn: per-vm-quota-requests）。Create a resource 是用來佈建全新資源，跟申請既有配額上限調整是兩回事，因此改判為 L。',
        },
    },
    399: {
        'stem_zh': '你需要建立一個新的 Azure 檔案共用 (file share)。你應該使用什麼服務？',
        'stem_en': 'You need to create a new Azure file share. What should you use?',
        'options': {
            'A': ('Storage accounts', '儲存體帳戶 (Storage accounts)'),
            'B': ('Virtual machines', '虛擬機器 (Virtual machines)'),
            'C': ('App Services', 'App Services'),
            'D': ('SQL databases', 'SQL 資料庫 (SQL databases)'),
            'E': ('Virtual networks', '虛擬網路 (Virtual networks)'),
        },
        'answer': ['A'],
        'explanations': {
            'A': 'Azure 檔案共用 (Azure Files) 是儲存體帳戶底下的一項資料服務，必須先建立（或使用既有的）儲存體帳戶，才能在其中建立檔案共用，因此是正確答案。',
            'B': '虛擬機器是運算服務，用來執行作業系統與應用程式，本身無法用來建立檔案共用，最多只是掛接檔案共用的用戶端。',
            'C': 'App Services 用於裝載 Web 應用程式、API 或行動應用程式後端，並非建立檔案共用的服務。',
            'D': 'SQL 資料庫是關聯式資料庫服務，用於儲存結構化資料表，與建立檔案共用無關。',
            'E': '虛擬網路是用來建立 Azure 資源之間隔離網路環境的服務，用於控制網路拓撲與連線，並不是用來建立檔案共用的服務。',
        },
    },
    403: {
        'stem_zh': '你需要為某個 Azure 訂用帳戶建立一個新的使用者。你應該使用什麼服務？',
        'stem_en': 'You need to create a new user for an Azure subscription. What should you use?',
        'options': {
            'A': ('Create a resource', '建立資源 (Create a resource)'),
            'B': ('Virtual machines', '虛擬機器 (Virtual machines)'),
            'C': ('Cost Management', '成本管理 (Cost Management)'),
            'D': ('Subscriptions', '訂用帳戶 (Subscriptions)'),
            'E': ('Azure Active Directory', 'Azure Active Directory'),
            'F': ('All resources', '所有資源 (All resources)'),
            'G': ('App Services', 'App Services'),
            'H': ('Resource groups', '資源群組 (Resource groups)'),
            'I': ('All services', '所有服務 (All services)'),
        },
        'answer': ['E'],
        'explanations': {
            'A': '建立資源用於佈建虛擬機器、儲存體帳戶等 Azure 資源，並不是用來建立使用者帳戶的功能。',
            'B': '虛擬機器用於管理運算執行個體，與建立使用者無關。',
            'C': '成本管理用於監控與分析 Azure 的花費，與建立使用者無關。',
            'D': '訂用帳戶用於管理計費與訂用帳戶層級設定，本身並不是建立使用者的入口。',
            'E': 'Azure Active Directory（現為 Microsoft Entra ID）是 Azure 的身分識別與存取管理服務，可在其中建立與管理使用者、群組及權限，因此是正確答案。',
            'F': '所有資源會列出訂用帳戶中的所有資源，並非用來建立使用者的功能。',
            'G': 'App Services 用於管理 Web 應用程式，與建立使用者無關。',
            'H': '資源群組用於管理資源的分組，與建立使用者無關。',
            'I': '所有服務用於瀏覽 Azure 提供的服務清單，並非建立使用者的直接入口。',
        },
    },
}
