#!/usr/bin/env python3
"""HOTSPOT「完成句子」→ 單選題，72 題自動化批次。

來源格式是「選出最適合填入句子空格的選項」，但空格所在的完整句子只存在於
截圖裡，PDF 文字層只留得下：考點說明（§1）、選項英文＋逐項中文分析
（§2，`az900_extract.extract_items()` 已經能可靠抽出來）。所以這裡沒辦法
「重建原句挖空」，而是依考點跟選項改寫成一個清楚的獨立問句——跟
`az900_manual.CHOICE`（117/148/157/314/438/445）用的是同一種做法。

`STEM_ZH`/`STEM_EN` 是我讀過 §1 考點說明跟每個選項的中文分析後寫的問句；
`OPTIONS_ZH` 是選項的中文翻譯，順序對應 `.build/sentence_dump.json` 裡
`options` 陣列的順序（也就是 PDF 原文出現的順序）。英文選項、判定、逐選項
解析全部沿用抽取結果，不重寫。
"""

STEM_ZH = {
    36: '在軟體即服務 (SaaS) 模型中，使用者的責任是下列何者？',
    38: '公有雲的其中一個特點是什麼？',
    40: '你的公司計畫將一個公開網站遷移到 Azure。規劃遷移時，你必須將下列哪一項納入考量？',
    50: 'Azure Site Recovery 的核心功能是什麼？',
    52: '下列哪一項 Azure 服務提供桌面與應用程式虛擬化？',
    68: 'Azure Cosmos DB 屬於哪一種雲端服務模型？',
    72: 'Azure 中用來防止資源被意外刪除或修改的功能稱為什麼？',
    81: 'Azure Site Recovery 的主要用途是什麼？',
    88: '「系統依需求動態調整資源，需求增加時自動擴展、需求減少時釋放資源」，這描述的是雲端運算的哪一項特性？',
    93: '「因為＿＿，你可以把應用程式與資料部署到全球各地的區域資料中心，確保使用者可以連到最近的資料中心」，空格應填入下列何者？',
    104: '你把一台虛擬機器移到另一個訂用帳戶。關於這台虛擬機器，下列敘述何者正確？',
    118: '可用性區域 (Availability Zone) 位於下列哪一個範圍之內？',
    132: '你有兩台虛擬機器 VM1 與 VM2，要確保 VM1 無法與 VM2 通訊。你應該怎麼做？',
    143: '下列哪一項 Azure 服務是包含微控制器單元 (MCU) 與客製化 Linux 作業系統、高度安全的物聯網解決方案？',
    147: 'Azure File Sync 是把內部部署檔案伺服器的資料同步到下列何者？',
    152: '為了能對一組資源做統一的權限管理與委派，你應該把這些資源部署到下列何者？',
    156: 'Azure 容器執行個體 (Azure Container Instances) 屬於哪一類服務？',
    158: 'Application Insights 是下列哪一項 Azure 服務的功能之一？',
    163: '下列何者正確描述了 Azure Blob 儲存體？',
    188: '你應該從哪裡存取合規性管理員 (Compliance Manager)？',
    189: 'Azure 資源管理員 (ARM) 範本提供的是下列何者？',
    209: '你想取得有關 Microsoft 雲端產品安全性、隱私權與合規性的資訊，應該查詢下列何者？',
    212: '下列哪一項 Azure 服務是基於 Apache Spark、專門用於大規模資料處理與機器學習的分析服務？',
    219: '你需要記錄訂用帳戶層級的活動（例如虛擬機器被關閉），應該使用下列何者？',
    230: 'Microsoft Sentinel 的智慧型手冊 (Playbook) 可以用來做什麼？',
    231: 'Azure 防火牆 (Azure Firewall) 中，允許把外部流量對應到虛擬網路內部特定伺服器的規則稱為什麼？',
    232: '應用程式安全性群組 (ASG) 讓你能以角色為基礎撰寫規則，這屬於保護 Azure 資源的哪一層？',
    246: 'NSG（網路安全性群組）用來控制虛擬機器輸入與輸出流量，這屬於哪一層的防護？',
    247: 'Microsoft Sentinel 的智慧型手冊 (Playbook) 可以用來做什麼？',
    251: '下列哪一項服務提供 Just-In-Time (JIT) 虛擬機器存取功能？',
    257: '要允許外部連線存取虛擬機器上 TCP 8080 埠，你應該設定下列何者？',
    265: '你的公司需要合規性報告，應該使用下列哪一項 Azure 服務？',
    281: '下列哪一項 Azure 服務提供單一登入 (SSO) 功能？',
    284: '如果 Azure 原則 (Azure Policy) 的拒絕效果套用到一個資源群組，該群組裡已經存在的不合規資源會發生什麼事？',
    288: '要求使用者提供兩種以上驗證因素以提高安全性，這是下列哪一項功能？',
    291: '你應該使用下列哪一項工具來檢視安全建議、威脅偵測結果與合規性報告？',
    296: '詳細說明微軟如何處理你的資料、處理目的與方式的文件稱為什麼？',
    297: '驗證使用者憑證（例如使用者名稱與密碼），確認使用者身分屬實的過程，稱為什麼？',
    298: 'Azure 原則的「計畫 (initiative) 定義」指的是什麼？',
    299: '下列哪一項功能可以讓組織跨多個訂用帳戶管理資源的合規性與原則？',
    306: '一個資源群組被加上了刪除鎖定，管理員必須先做什麼才能刪除該資源群組？',
    307: '確認一位使用者或服務身分的過程，稱為什麼？',
    310: 'Azure 服務開放給所有 Azure 客戶試用並提供意見回饋的生命週期階段，稱為什麼？',
    317: '你的 Azure 免費試用帳戶到期後，你將無法執行下列哪一項操作？',
    329: '你想設定預算上限，並在花費超過門檻時收到電子郵件通知，應該使用下列何者？',
    338: '如果 Azure 服務因中斷而未達成 SLA 承諾，微軟的補償方式是下列何者？',
    342: '下列哪一種虛擬機器可以用大幅折扣的價格使用 Azure 未用完的運算容量，但可能因容量需求變化而被中斷？',
    343: '要停止一台虛擬機器並確實停止計費（儲存費用除外），你應該怎麼做？',
    349: 'Azure AD 中，依登入時收集到的訊號（例如使用者位置、裝置狀態）動態決定要允許還是拒絕存取要求的功能稱為什麼？',
    352: 'Azure 防火牆中，允許把外部流量對應到虛擬網路內部資源的規則稱為什麼？',
    372: '公開預覽 (Public Preview) 階段的 Azure 服務有什麼特性？',
    388: '確保使用者能夠計算並預測雲端服務成本，這是雲端運算的哪一項特性？',
    391: '組織在自己的基礎設施上執行雲端服務、不需依賴傳統資料中心，這描述的是下列何種雲端部署模型？',
    397: 'Premium block blobs 儲存體帳戶支援下列哪一種備援選項？',
    392: '雲端應用程式能依需求動態配置與釋放資源，藉此因應負載變化，這是雲端運算的哪一項特性？',
    393: '下列哪一項 Azure 服務是一種無伺服器運算服務，能執行應用程式程式碼而不需管理底層伺服器？',
    404: 'Azure 資源管理員 (ARM) 範本使用的是哪一種檔案格式？',
    406: '服務等級協定 (SLA) 定義的是下列何者？',
    410: '要取得 Azure 服務、區域與資源的健康狀態，包括服務中斷與維護通知，你應該使用下列何者？',
    413: 'Azure Cosmos DB 提供平台層級的功能，讓開發人員不需管理底層基礎設施即可儲存與管理資料，這屬於哪一種雲端服務模型？',
    421: '你想設定預算上限，並在花費達到門檻時收到電子郵件警示，應該使用下列何者？',
    422: '透過下列哪一項授權方案，你可以把現有的 Windows Server 或 Microsoft SQL Server 授權移轉到 Azure 虛擬機器（即 Azure Hybrid Benefit）？',
    436: '下列哪一項 Azure 服務可以把 Azure 的管理與監視能力延伸到混合雲與多雲環境？',
    439: '如果 Azure 服務中斷達到 SLA 規定的門檻，微軟的補償方式是下列何者？',
    446: 'Azure 儲存體的非經常 (Cool) 存取層適合用於下列哪一種情境？',
    447: '要取得 Azure 服務與區域的整體健康狀態概覽，包括計畫性維護、服務問題與健康建議，你應該使用下列何者？',
    449: '把虛擬機器分組到不同的更新網域與容錯網域，藉此提高應用程式可用性與容錯能力，這項功能稱為什麼？',
    451: 'Azure 原則 (Azure Policy) 可以指派到下列哪一個層級？',
    458: '資源鎖定可以套用到下列哪一種物件，以防止其中的資源被意外刪除或修改？',
    460: 'Azure 資源部署時需要指定的地理位置類型稱為什麼？',
    466: '下列哪一項 Azure 服務會針對成本最佳化提供建議？',
    473: '服務等級協定 (SLA) 通常以百分比定義服務的正常運作時間，這代表的是服務的哪一項指標？',
}

STEM_EN = {
    36: 'With a software as a service (SaaS) model, what is the responsibility of the user?',
    38: 'What is a characteristic of the public cloud?',
    40: 'Your company plans to migrate a public website to Azure. What must you plan for when migrating?',
    50: 'What is the core function of Azure Site Recovery?',
    52: 'Which Azure service provides desktop and app virtualization?',
    68: 'Which cloud service model does Azure Cosmos DB belong to?',
    72: 'What is the Azure feature used to prevent a resource from being accidentally deleted or modified?',
    81: 'What is the primary purpose of Azure Site Recovery?',
    88: 'Which cloud computing characteristic is described as the ability to dynamically adjust resources based on demand?',
    93: 'Because of ______, you can deploy apps and data to regional datacenters around the globe, ensuring customers are served from the nearest datacenter. What fills the blank?',
    104: 'You move a virtual machine to a different subscription. Which statement about the virtual machine is correct?',
    118: 'An availability zone exists within which of the following?',
    132: 'You have two virtual machines, VM1 and VM2. You need to ensure that VM1 cannot communicate with VM2. What should you do?',
    143: 'Which Azure service is a highly secured IoT solution that includes a microcontroller unit (MCU) and a customized Linux operating system?',
    147: 'Azure File Sync synchronizes data from an on-premises file server to what?',
    152: 'To manage and delegate permissions for a group of resources together, you should deploy them to what?',
    156: 'Azure Container Instances belongs to which category of service?',
    158: 'Application Insights is a feature of which Azure service?',
    163: 'Which statement correctly describes Azure Blob storage?',
    188: 'Where should you access Compliance Manager from?',
    189: 'What do Azure Resource Manager (ARM) templates provide?',
    209: 'Where can you find information about the security, privacy, and compliance of Microsoft cloud products?',
    212: 'Which Azure service is an Apache Spark-based analytics service used for large-scale data processing and machine learning?',
    219: 'You need to log subscription-level activities, such as shutting down a virtual machine. What should you use?',
    230: 'What can a Microsoft Sentinel playbook be used for?',
    231: 'In Azure Firewall, what are the rules called that map external traffic to a specific server inside a virtual network?',
    232: 'Application security groups let you write rules based on roles. Which layer of protection does this belong to?',
    246: 'NSGs control inbound and outbound traffic for virtual machines. Which layer of protection does this belong to?',
    247: 'What can a Microsoft Sentinel playbook be used for?',
    251: 'Which service provides Just-In-Time (JIT) VM access?',
    257: 'To allow external connections to TCP port 8080 on a virtual machine, what should you configure?',
    265: 'Your company needs compliance reports. Which Azure service should you use?',
    281: 'Which Azure service provides single sign-on (SSO)?',
    284: 'If a deny-effect Azure Policy is applied to a resource group, what happens to noncompliant resources that already exist in the group?',
    288: 'Requiring a user to provide two or more verification factors to improve security is an example of what?',
    291: 'Which tool should you use to view security recommendations, threat detection results, and compliance reports?',
    296: 'What is the document called that describes how Microsoft processes your data, for what purposes, and how?',
    297: 'The process of verifying a user\'s credentials, such as a username and password, to confirm their identity is called what?',
    298: 'What does an Azure Policy initiative definition refer to?',
    299: 'Which feature allows an organization to manage compliance and policies for resources across multiple subscriptions?',
    306: 'A resource group has a delete lock applied. What must an administrator do before the resource group can be deleted?',
    307: 'The process of confirming the identity of a user or service is called what?',
    310: 'What is the lifecycle stage called in which an Azure service is available to all Azure customers to try and provide feedback on?',
    317: 'After your Azure free trial account expires, which of the following will you be unable to do?',
    329: 'You want to set a spending limit and receive an email notification when costs exceed a threshold. What should you use?',
    338: 'If an Azure service fails to meet its SLA due to an outage, how does Microsoft compensate you?',
    342: 'Which type of virtual machine lets you use unused Azure compute capacity at a deep discount, but may be evicted when capacity is needed elsewhere?',
    343: 'To stop a virtual machine and ensure that compute billing actually stops (aside from storage costs), what should you do?',
    349: 'In Azure AD, what is the feature called that dynamically allows or denies sign-in requests based on signals such as user location and device state?',
    352: 'In Azure Firewall, what are the rules called that map external traffic to resources inside a virtual network?',
    372: 'What is a characteristic of an Azure service in public preview?',
    388: 'Ensuring that customers can calculate and forecast the cost of a cloud service is an example of which cloud computing characteristic?',
    391: 'An organization runs cloud services on its own infrastructure, without relying on a traditional datacenter. Which cloud deployment model does this describe?',
    397: 'Which redundancy option is supported by a Premium block blobs storage account?',
    392: 'The ability of a cloud application to dynamically allocate and release resources in response to changes in demand is an example of which characteristic?',
    393: 'Which Azure service is a serverless compute service that runs application code without you having to manage the underlying server?',
    404: 'Which file format do Azure Resource Manager (ARM) templates use?',
    406: 'What does a Service Level Agreement (SLA) define?',
    410: 'You need the health status of Azure services, regions, and resources, including outages and maintenance notifications. What should you use?',
    413: 'Azure Cosmos DB provides platform-level capabilities that let developers store and manage data without managing the underlying infrastructure. Which cloud service model does this describe?',
    421: 'You want to set a spending limit and receive an email alert when costs reach a threshold. What should you use?',
    422: 'Which licensing program lets you transfer existing Windows Server or Microsoft SQL Server licenses to Azure virtual machines (Azure Hybrid Benefit)?',
    436: 'Which Azure service extends Azure management and monitoring capabilities to hybrid and multicloud environments?',
    439: 'If an Azure service outage exceeds the SLA threshold, how does Microsoft compensate you?',
    446: 'The Cool access tier in Azure Storage is best suited for which scenario?',
    447: 'You need an overview of the health of Azure services and regions, including planned maintenance, service issues, and health advisories. What should you use?',
    449: 'Grouping virtual machines across update domains and fault domains to improve application availability and fault tolerance is called what?',
    451: 'To which of the following levels can an Azure Policy be assigned?',
    458: 'A resource lock can be applied to which of the following, to prevent resources within it from being accidentally deleted or modified?',
    460: 'What is the type of geographic location called that you must specify when deploying an Azure resource?',
    466: 'Which Azure service provides recommendations for cost optimization?',
    473: 'A Service Level Agreement (SLA) typically defines service uptime as a percentage. Which metric does this represent?',
}

# 選項的中文翻譯，順序對應 .build/sentence_dump.json 的 options 陣列。
OPTIONS_ZH = {
    36: ['設定高可用性', '定義可調整規模的規則', '安裝 SaaS 解決方案', '設定 SaaS 解決方案'],
    38: ['在私有雲中', '在混合雲中', '在公有雲中', '在 Hyper-V 主機上'],
    40: ['部署 VPN', '支付每月使用費用', '支付把所有網站資料移轉到 Azure 的費用', '減少連到網站的連線數'],
    50: ['容錯 (fault tolerance)', '災害復原 (disaster recovery)', '彈性 (elasticity)', '高可用性 (high availability)'],
    52: ['可用性設定組', 'Azure Spot 虛擬機器', 'Azure Virtual Desktop', 'Azure 虛擬機器擴展集'],
    68: ['平台即服務 (PaaS)', '基礎設施即服務 (IaaS)', '無伺服器 (serverless)', '軟體即服務 (SaaS)'],
    72: ['藍圖 (blueprint)', '鎖定 (lock)', '原則 (policy)', '服務端點 (service endpoint)'],
    81: ['容錯 (fault tolerance)', '災害復原 (disaster recovery)', '彈性 (elasticity)', '高可用性 (high availability)'],
    88: ['敏捷性 (agility)', '彈性 (elasticity)', '地理分散 (geo-distribution)', '可預測性 (predictability)'],
    93: ['彈性 (Elasticity)', '地理分散 (Geo-distribution)', '高可用性 (High availability)', '可調整規模性 (Scalability)'],
    104: [
        '這台虛擬機器無法移到新的訂用帳戶。',
        '這台虛擬機器可以移到新的訂用帳戶。',
        '這台虛擬機器只有在全都位於同一個資源群組時，才能移到新的訂用帳戶。',
        '這台虛擬機器只有在執行 Windows Server 2016 時，才能移到新的訂用帳戶。',
    ],
    118: ['橫跨兩個大陸', '單一 Azure 區域內', '跨越多個 Azure 區域', '單一 Azure 資料中心內'],
    132: ['部署到不同的虛擬網路', '執行跟其他虛擬機器不同的作業系統', '部署到不同的資源群組', '設定兩個網路介面'],
    143: ['Azure Arc', 'Azure IoT Central', 'Azure IoT Hub', 'Azure Sphere'],
    147: ['Azure Blob 容器', 'Data Lake 儲存體容器', '檔案共用', '佇列'],
    152: ['同一個 Azure 區域', '使用同一份 Azure Resource Manager 範本', '同一個資源群組', '同一個可用性區域'],
    156: ['計算服務', '身分服務', '網路服務', '儲存服務'],
    158: ['Azure 顧問 (Azure Advisor)', 'Azure 應用程式閘道', 'Azure Arc', 'Azure 監視器 (Azure Monitor)'],
    163: [
        '用來把訊息排入佇列、可靠傳遞給應用程式的資料儲存體',
        '可以對應為網路磁碟機的檔案共用',
        '用於非關聯式結構化資料的索引鍵／屬性儲存體',
        '針對超大型物件（例如影片檔案、點陣圖）最佳化的儲存服務',
    ],
    188: ['Azure Active Directory 系統管理中心', 'Azure 入口網站', 'Microsoft 365 系統管理中心', 'Microsoft Service Trust Portal'],
    189: ['Azure 原則提供的是', '資源群組提供的是', 'Azure 資源管理員範本提供的是', '管理群組提供的是'],
    209: ['Microsoft 365 合規性系統管理中心', 'Microsoft 365 Defender 入口網站', 'Azure 入口網站中的 Microsoft Defender for Cloud', 'Microsoft 信任中心 (Trust Center)'],
    212: ['Azure Databricks', 'Azure Data Factory', 'Azure DevOps', 'Azure Synapse Analytics'],
    219: ['Azure 存取控制 (IAM)', 'Azure 事件中樞', 'Azure 活動記錄', 'Azure 服務健康狀態'],
    230: ['自動回應威脅', '收集來自 Azure 服務的資料', '指定資料保留的時間長度', '儲存密碼與憑證'],
    231: ['應用程式規則', '網路位址轉譯 (NAT) 規則', '網路規則', '服務標籤'],
    232: ['應用程式層', '計算層', '網路層', '周邊層'],
    246: ['應用程式層', '計算層', '網路層', '周邊層'],
    247: ['自動回應威脅', '將連接器收集到的資料視覺化', '指定資料保留的時間長度', '儲存密碼與憑證'],
    251: ['Azure Bastion', 'Azure 防火牆 (Azure Firewall)', 'Azure Front Door', 'Azure 安全中心 (Azure Security Center)'],
    257: ['網路安全性群組 (NSG)', '虛擬網路閘道', '虛擬網路', '路由表'],
    265: ['Azure 顧問 (Azure Advisor)', 'Azure Analysis Services', 'Azure 監視器 (Azure Monitor)', 'Azure 安全中心 (Azure Security Center)'],
    281: ['Azure 中的應用程式安全性群組', 'Azure Active Directory (Azure AD)', 'Azure Key Vault', 'Azure 安全中心 (Azure Security Center)'],
    284: ['會被自動刪除', '會被自動搬到另一個資源群組', '會繼續正常運作', '會變成唯讀物件'],
    288: ['企業對客戶 (B2C) 身分服務', '受控識別', '多重要素驗證 (MFA)', '角色型存取控制 (RBAC)'],
    291: ['Microsoft Defender for Cloud', 'Microsoft Defender for Identity 系統管理中心', 'Microsoft 365 合規性中心', 'Microsoft Service Trust Portal'],
    296: ['Microsoft 線上服務隱私權聲明', 'Microsoft 產品條款', 'Microsoft 線上服務等級協定', 'Microsoft Azure 線上訂閱合約'],
    297: ['授權 (Authorization)', '驗證 (Authentication)', '同盟 (Federation)', '票證 (Ticketing)'],
    298: ['原則定義的集合', 'Azure 原則指派的集合', 'Azure 藍圖定義的群組', '角色型存取控制 (RBAC) 角色指派的群組'],
    299: ['資源群組', '管理群組', 'Azure 原則', 'Azure App Service 方案'],
    306: [
        '管理員必須是全域管理員群組的成員',
        '必須先移除刪除鎖定，管理員才能',
        '必須先修改 Azure 原則，管理員才能',
        '必須先新增 Azure 標記，管理員才能',
    ],
    307: ['驗證 (Authentication)', '授權 (Authorization)', '條件式存取 (Conditional Access)', '同步 (Synchronization)'],
    310: ['公開預覽 (public preview)', '私人預覽 (private preview)', '開發階段 (development)', '企業合約 (EA) 訂用帳戶'],
    317: ['建立額外的 Azure Active Directory (Azure AD) 使用者帳戶', '啟動一台既有的 Azure 虛擬機器', '存取儲存在 Azure 的資料', '存取 Azure 入口網站'],
    329: ['顧問建議', '存取控制 (IAM)', '預算警示', '合規性'],
    338: ['退款到你的銀行帳戶', '把資源移轉到另一個訂用帳戶', '把信用額度存入你的 Azure 帳戶', '寄給你可以兌換 Azure 額度的優惠碼'],
    342: ['Azure 容器執行個體', 'Azure 保留虛擬機器執行個體', 'Azure Spot 虛擬機器執行個體', 'Azure 虛擬機器擴展集'],
    343: ['在遠端桌面工作階段中中斷這台虛擬機器的連線', '在遠端桌面工作階段中把虛擬機器設為睡眠模式', '在 Azure 入口網站為這台虛擬機器選擇「停止」', '在遠端桌面工作階段中關閉這台虛擬機器'],
    349: ['受控識別', '條件式存取 (Conditional Access)', 'Microsoft Intune'],
    352: ['應用程式規則', '網路位址轉譯 (NAT) 規則', '網路規則', '服務標籤'],
    372: ['不會提供任何文件', '只能透過 Azure CLI 設定', '不包含在服務等級協定內', '只能透過 Azure 入口網站設定'],
    388: ['敏捷性 (Agility)', '彈性 (Elasticity)', '高可用性 (High availability)', '可預測性 (Predictability)'],
    391: ['在私有雲中', '在混合雲中', '在公有雲中', '在 Hyper-V 主機上'],
    392: ['彈性 (Elasticity)', '治理 (Governance)', '高可用性 (High availability)', '可預測性 (Predictability)', '可靠性 (Reliability)'],
    393: ['Azure DevOps 管線', 'Azure Resource Manager 範本', 'Azure 應用程式閘道', 'Azure Functions'],
    397: ['本機備援儲存體 (LRS)', '區域備援儲存體 (ZRS)'],
    404: ['CSV 格式', 'HTML 格式', 'JSON 格式', 'XML 格式'],
    406: ['對未來技術藍圖功能的承諾', '對效能標準的承諾', '可用基礎設施的最大可調整規模上限', '可用基礎設施的最小可調整規模上限'],
    410: ['應用程式深入解析 (Application Insights)', 'Azure 顧問 (Azure Advisor)', 'Azure 服務健康狀態 (Azure Service Health)'],
    413: ['平台即服務 (PaaS)', '基礎設施即服務 (IaaS)', '內容即服務', '軟體即服務 (SaaS)'],
    421: ['顧問建議', '存取控制 (IAM)', '預算警示', '合規性'],
    422: ['使用者授權合約 (EULA)', 'Microsoft 產品生命週期原則', 'Software Assurance', ],
    436: ['Azure AD Connect', 'Azure Arc', 'Azure Front Door', 'Azure 原則 (Azure Policy)'],
    439: ['退款到你的銀行帳戶', '把資源移轉到另一個訂用帳戶', '把信用額度存入你的 Azure 帳戶', '寄給你可以兌換 Azure 額度的優惠碼'],
    446: ['適用於不常被存取、且至少要儲存 30 天的資料', '適用於很少被存取、至少要儲存 180 天、且延遲需求有彈性的資料', '適用於儲存經常被存取的資料'],
    447: ['Azure 監視器 (Azure Monitor)', 'Azure 資源健康狀態', 'Azure 服務健康狀態', 'Azure 狀態頁'],
    449: ['可用性設定組', '可用性區域', 'Azure 負載平衡器', 'Azure 虛擬機器擴展集'],
    451: ['容器應用程式', '資源群組', '資源鎖定', '安全性群組'],
    458: ['系統管理單位', 'Azure 原則', 'Azure 訂用帳戶', '使用者帳戶'],
    460: ['地理位置 (geography)', '區域 (region)', '資料中心 (datacenter)', '城市 (city)'],
    466: ['應用程式深入解析 (Application Insights)', 'Azure 顧問 (Azure Advisor)', 'Azure 資源標記', 'Azure 服務健康狀態'],
    473: ['可用性 (availability)', '彈性 (elasticity)', '可靠性 (reliability)', '可調整規模性 (scalability)'],
}

# id 397 的英文選項在 §2 抽取失敗（版面問題），直接覆寫成從分析文字裡讀到的原文。
OPTIONS_EN_OVERRIDE = {
    397: ['locally-redundant storage (LRS)', 'zone-redundant storage (ZRS)'],
}
